### ISSUE TITLE
Исправления перед релизом

### ISSUE THREAD

**Issue by blackst0ne** [geophystech/geophystech.ru#1]
Требуется исправить перед выпуском 2.0 некоторые моменты по вёрстке и контенту.

**Comment by blackst0ne** [comment]
**Поправлено**

![image](https://user-images.githubusercontent.com/3518847/29957516-9ad323ee-8f39-11e7-941d-9806ae2fc580.png)

Нужно убрать блок Услуги.

**Comment by blackst0ne** [comment]
![image](https://user-images.githubusercontent.com/3518847/29957550-d3bd3f46-8f39-11e7-832d-5b4629dae4c6.png)

Что с картинкой?

**Comment by blackst0ne** [comment]
**Поправлено**

В разделе инженерная геофизика георадарные работы нужно убрать в самый конец.

**Comment by blackst0ne** [comment]
**Поправлено**

Перед георадарными раотами разместить `Оценка параметров собственных колебаний зданий`

**Comment by blackst0ne** [comment]
**Поправлено**

![image](https://user-images.githubusercontent.com/3518847/29957841-4f2dbf92-8f3b-11e7-8430-566df722fd0a.png)

**Comment by blackst0ne** [comment]
**Поправлено**

В услугу сейсмометрического контроля нужно вставить вот это:

Методы проверки и средства обеспечения сейсмостойкости строительных конструкций опираются на накопленный многовековой фактический материал по последствиям сильных землетрясений и опыт их предотвращения или хотя бы минимизации, максимального снижения угрозы сейсмических потрясений для жизни людей, продуктов их деятельности и окружающей среды. Расчетное определение сейсмостойкости зданий и сооружений является обязательным этапом при проектировании новых видов или модификаций существующих конструкций оборудования в сейсмостойком исполнении [п. 4.8 СП 14.13330.2014 (Строительство в сейсмических районах СНиП II-7-81*) и Градостроительного кодекса Российской Федерации для производственных объектов I и II класса опасности]. Этими же кодами определяется, что сейсмометрический контроль зданий и сооружений является обязательным для объектов с повышенным уровнем ответственности. К таковым относятся гидротехнические сооружения, электростанции, объекты нефтегазового комплекса, а также школы, больницы и т.д.

Действующими строительными нормами и правилами определяется подход по обеспечению сейсмостойкого исполнения конструкций по уровню ответственности. Так к нормальным и ответственным объектам предъявляются следующие требования: конструкция должна выдержать сейсмические нагрузки одного максимального землетрясения и нескольких проектных землетрясений, при этом жизнедеятельность конструкции не должна быть нарушена.
Непрерывный сейсмометрический контроль зданий и сооружений призван определять текущие сейсмические нагрузки на конструкции и сравнивать их со значениями, заложенными при проектировании. Даже при относительно слабых сейсмических воздействиях могут появляться визуально неидентифицируемые дефекты, которые могут привести к разрушению конструкции. Наличие таких дефектов приводит к изменению формы спектра реакции сооружения, что позволяет обнаружить их на ранних стадиях развития. 

Основными целями настоящей услуги являются обеспечение защиты жизни и здоровья населения и сведение к минимуму последствий от сейсмических воздействий на здания и инженерные сооружения, учет сейсмогеологической обстановки. 

Для выполнения работ на объектах будет развёрнута современная система сейсмометрического контроля, обеспечивающей безопасность объектам жизнедеятельности и промышленным объектам, экономическую целесообразность и полное соответствие строительным нормам и правилам РФ [п. 4.8 СП 14.13330.2014 (Строительство в сейсмических районах СНиП II-7-81*) и Градостроительного кодекса Российской Федерации для производственных объектов I и II класса опасности].

**Comment by blackst0ne** [comment]
**Поправлено**

![image](https://user-images.githubusercontent.com/3518847/29957997-3efde772-8f3c-11e7-8322-049e49e849db.png)
Рекомендации по расположению датчиков сейсмометрического контроля от Строительного исследовательского института Цукубы


Эту картинку нужно разместить для услуги сейсмометрического контроля.

**Comment by blackst0ne** [comment]
**Поправлено**

![image](https://user-images.githubusercontent.com/3518847/29958120-d0c6d498-8f3c-11e7-9b4c-68899baa02e9.png)

**Comment by blackst0ne** [comment]
**Поправлено**

> Эту картинку нужно разместить для услуги сейсмометрического контроля.

В тексте вставить эту картинку и написать: Рекомендации по расположению датчиков сейсмометрического контроля от Строительного исследовательского института Цукубы

**Comment by blackst0ne** [comment]
**Поправлено**

![image](https://user-images.githubusercontent.com/3518847/29958183-19f33058-8f3d-11e7-97f4-1ec7aef14ef4.png)

Это везде жирным надо.

**Comment by blackst0ne** [comment]
**Поправлено**

![image](https://user-images.githubusercontent.com/3518847/29958221-5c2b9f50-8f3d-11e7-9b8b-4544ec3901c5.png)

Вот эту картинку нужно вставить в тексте для элеткрораведки рядом с описанием оборудования.

**Comment by blackst0ne** [comment]
**Поправлено**

![image](https://user-images.githubusercontent.com/3518847/29958265-870fe992-8f3d-11e7-9749-89437092db53.png)

![image](https://user-images.githubusercontent.com/3518847/29958267-8a08a1ac-8f3d-11e7-86e1-17407202f47b.png)

Примеры 1D разрезов удельного электрического сопротивления по данным вертикального электрического зондирования (ВЭЗ). Вставить в электроразведку.

**Comment by blackst0ne** [comment]
**Поправлено**

![image](https://user-images.githubusercontent.com/3518847/29958309-d466fa00-8f3d-11e7-859e-f06b752f9774.png)

Пример 2D разрезов удельного сопротивления по данным электроразведочных работ в режиме электротомографии

**Comment by blackst0ne** [comment]
Вставить в описание электротомографии:

Для уточнения строения грунтов по профилям сейсморазведочных работ (подтверждения уровня верхнего слоя крепкой породы) применяется электротомография. Результаты будут представлены в виде 2D-разрезов с уточнением и дополнением информации сейсмических работ информацией о пустотах, мерзлотных линзах и других неоднородностях. Профиля электроразведочных работ выбираются по линиям раскладки сейсмических кос на исследуемых участках (длина расстановки электродов 94 м, шаг между электродами 2 метра).

Полевые электроразведочные работы производились с помощью электроразведочной аппаратуры: (таблица в документе)

> Вот эту картинку нужно вставить на электроразведку. Если нельзя вставить на краткое опаисание, значит нужно вставить в текст

это как раз фото скалы, можно привязать к этому описанию с таблицей.

[Таблица 1.docx](https://github.com/geophystech/geophystech.ru/files/1269382/1.docx)

**Comment by blackst0ne** [comment]
**Поправлено**

![image](https://user-images.githubusercontent.com/3518847/29958506-d01603be-8f3e-11e7-8520-a65e98489596.png)

^^^**Эта картинка не удачная, думаю её надо отовсюду убрать.** 

Лучше с твиттера взять например вот эту:

![image](https://user-images.githubusercontent.com/3518847/29958531-e453dfea-8f3e-11e7-9bd8-731b99b1c9f6.png)


Она прямоугольная как раз. её можно на страницы услуги.

**Comment by blackst0ne** [comment]
[Таблица 2.docx](https://github.com/geophystech/geophystech.ru/files/1269400/2.docx)

Вставить в сейсморазведку по аналогии с элеткроразведкой.

**Comment by blackst0ne** [comment]
**Поправлено**


Из описания сейсмического микрорайонирования:

- фото с грязной машиной убрать

![image](https://user-images.githubusercontent.com/3518847/29958707-ca7af760-8f3f-11e7-8a75-b1f3a14c8c63.png)

это вставить `Определение активности сегментов тектонического разлома`

![image](https://user-images.githubusercontent.com/3518847/29958727-ef2b7418-8f3f-11e7-9f17-8c500bcb09cd.png)

Это вставить `Зависимости интенсивности пикового ускорения грунта (PGA) от периода повторяемости для рассматриваемой площадки`

![image](https://user-images.githubusercontent.com/3518847/29958770-1d3c5a98-8f40-11e7-997d-cc7bf3dee371.png)

Это вставить `Результаты деагрегационного анализа позволяют оценить характеристические землетрясения, то есть наиболее вероятные для заданного уровня сейсмических воздействий`

![image](https://user-images.githubusercontent.com/3518847/29958789-338a9b02-8f40-11e7-82d8-e5671baa7ced.png)

Это вставить: `Подбор акселерограмм-аналогов на основе проектного спектра реакции для заданного периода повторяемости по мировым источникам и собственному банку данных `

![image](https://user-images.githubusercontent.com/3518847/29958832-66bc6f1e-8f40-11e7-99fc-b573c67ecace.png)

Вот эту картинку нужно вставить и написать: `Основные этапы СМР` Ну съехавшие буквы можно поправить.

**Comment by blackst0ne** [comment]
**Всё что я здесь написал есть в презентации. Синии рамки можно убрать если сохранить исходник из презентации.**

**Comment by blackst0ne** [comment]
Вставить ссылки на презентации на главной.

**Comment by blackst0ne** [comment]
![image](https://user-images.githubusercontent.com/3518847/29959539-9506c3d0-8f43-11e7-9dc9-0894573f0867.png)

ссылки на файлы

**Comment by blackst0ne** [comment]
![image](https://user-images.githubusercontent.com/3518847/29959550-a8d913f4-8f43-11e7-8e00-6699b095120a.png)

Слово прочее съехало.

**Comment by blackst0ne** [comment]
**Поправлено**

**НА ГЛАВНОЙ** в инженерную геофизику поставить Костю с кувалдой

**Comment by blackst0ne** [comment]
**Поправлено**

**НА ГЛАВНОЙ** в сейсмический мониторинг поставить этот скриншот
![image](https://user-images.githubusercontent.com/3518847/29959679-34418db8-8f44-11e7-9a45-e4baa5077804.png)

Или переснять по удачнее: https://eqalert.ru/ru/events/QgpAn7OW

**Comment by blackst0ne** [comment]
На главной заменить наши партнёры на наши клиенты и партнёры

**Comment by blackst0ne** [comment]
@jamm1985 

> Что с картинкой?

Её просто нет. Нужно вставить какую-нибудь.

**Comment by blackst0ne** [comment]
> В услугу сейсмометрического контроля нужно вставить вот это:

Куда именно это нужно вставить? В любое место в дополнение к существующему тексту?

**Comment by blackst0ne** [comment]
> Куда именно это нужно вставить? В любое место в дополнение к существующему тексту?

Да в дополнение. Можно до раздела `область применения`.

**Comment by blackst0ne** [comment]
> Её просто нет. Нужно вставить какую-нибудь.

ну я там отписал уже ...

**Comment by blackst0ne** [comment]
@jamm1985 выложи, пожалуйста, тиблицы сюда ещё раз.

**Comment by blackst0ne** [comment]
> Слово прочее съехало.

Оно не съехало. Это такой же пункт меню, как и остальные. 
Текст отсюда: https://docs.google.com/document/d/17jgPS9tRNRBKjkx0tUE6j2Fv1v1o8_KCLxrxfs_zzKE/edit#heading=h.f0s0u3v77lw

**Comment by jamm1985** [comment]
Прочее - это не пункт меню, это часть последнего кода

**Comment by blackst0ne** [comment]
> Прочее - это не пункт меню, это часть последнего кода

"72.19 Научные исследования и разработки в области естественных и технических наук прочие" - так, что ли?
Звучит очень криво. :slightly_smiling_face:

**Comment by blackst0ne** [comment]
> ссылки на файлы

А на какие файлы-то? :)

**Comment by blackst0ne** [comment]
> Вставить ссылки на презентации на главной.

Напомни, пожалуйста, на какие презентации вставляем ссылки? 
На `2017-04-25 Общая презентация.pptx` и `2017-08-02 Инженерная геофизика.pptx`?

**Comment by blackst0ne** [comment]
@jamm1985 я поправил всё, что не требует ответа от тебя. 
В каждом замечании выше добавил **Поправлено** для определения сделано/не сделано.

**Comment by jamm1985** [comment]
[Таблица 2.docx](https://github.com/geophystech/geophystech.ru/files/1273877/2.docx)
[Таблица 1.docx](https://github.com/geophystech/geophystech.ru/files/1273879/1.docx)

**Comment by jamm1985** [comment]
https://drive.google.com/open?id=0B2f7GTVNnTNaRU1iQjZ0djNHSms

https://drive.google.com/open?id=0B2f7GTVNnTNaTnlSZDIySHVwR1E

https://drive.google.com/open?id=0B2f7GTVNnTNaRDhGeDVlTWNBNmM

https://drive.google.com/open?id=0B2f7GTVNnTNaTDljamI0YWtJdVE

**Comment by jamm1985** [comment]
[2016_07_13 НК Роснефть об аккредитации.pdf](https://github.com/geophystech/geophystech.ru/files/1273915/2016_07_13.pdf)
