### ISSUE TITLE
Дополнить услугу "Электротомография"

### ISSUE THREAD

**Issue by blackst0ne** [geophystech/geophystech.ru#14]
Вставить в описание электротомографии:

Для уточнения строения грунтов по профилям сейсморазведочных работ (подтверждения уровня верхнего слоя крепкой породы) применяется электротомография. Результаты будут представлены в виде 2D-разрезов с уточнением и дополнением информации сейсмических работ информацией о пустотах, мерзлотных линзах и других неоднородностях. Профиля электроразведочных работ выбираются по линиям раскладки сейсмических кос на исследуемых участках (длина расстановки электродов 94 м, шаг между электродами 2 метра).

Полевые электроразведочные работы производятся с помощью электроразведочной аппаратуры: (таблица в документе)

Вот эту картинку нужно вставить на электроразведку. Если нельзя вставить на краткое опаисание, значит нужно вставить в текст
это как раз фото скалы, можно привязать к этому описанию с таблицей.

https://github.com/geophystech/geophystech.ru/files/1273879/1.docx

**Comment by blackst0ne** [comment]
@jamm1985 

1. Электротомография - это [вот это](https://geophystech.ru/services/electric-exploration/)? 
2. В какое место нужно вставить текст? Или на мой выбор? :slightly_smiling_face: 
3. Таблица с характеристиками Скалы - куда вставлять? Прямо в текст услуги? Или в виде ссылки на документ?
4. Если таблицу помещать в виде текста (таблицы) прямо на страницу, то под какую фотку? Под [вот эту](https://geophystech.ru/images/services/engineering-geophysics/engineering-19.png)?

**Comment by jamm1985** [comment]
> Электротомография - это вот это?

> В какое место нужно вставить текст? Или на мой выбор?

после `II этап. Обработка данных с помощью специализированного программного обеспечения, построение геоэлектрических разрезов, составление отчета.`

После фотки которую ты указал.

**Comment by jamm1985** [comment]
@blackst0ne а где описание то из ТЗ?

**Comment by blackst0ne** [comment]
Готово.
