### ISSUE TITLE
Дополнить услугу "Сейсморазведка"

### ISSUE THREAD

**Issue by blackst0ne** [geophystech/geophystech.ru#15]
https://github.com/geophystech/geophystech.ru/files/1273877/2.docx

Вставить в сейсморазведку по аналогии с элеткроразведкой.

**Comment by blackst0ne** [comment]
@jamm1985 

1. Таблицы вставлять прямо на страницу услуги? Или просто добавить ссылку на документ?
2. Куда помещать? Или на мой выбор?

**Comment by jamm1985** [comment]
Прямо в услугу, лучше где нибудь рядом с фоткой оборудования
