### ISSUE TITLE
Ключевые слова

### ISSUE THREAD

**Issue by jamm1985** [geophystech/geophystech.ru#34]
Мониторинг естественной и наведённой сейсмичности:
- сейсмический мониторинг, сейсмологический мониторинг, геодинамический мониторинг, техногенная сейсмичность, естественная сейсмичность, землетрясение, интенсивность землетрясения, сейсмограмма, сейсмическая станция, сейсмостанция, магнитуда, MSK64

Мониторинг сильных движений грунта
- сильные движения грунта, эксплуатация промышленных объектов, сейсморазрыв, PGA, PGV, PGD, смещение земной поверхности, монтаж станций, магистральные объекты, трубопроводы

Сейсмометрический контроль зданий и сооружений
- Сейсмометрический контроль, сейсмостойкость, Строительство в сейсмических районах, гидротехнические сооружения, электростанции, сейсмические нагрузки, разрушение конструкции, спектр реакции, защита при ЧС, ТЭЦ, ГЭС, ГРЭС, АЭС, сейсмостойкое строительство

Сейсмическое микрорайонирование:
- Сейсмическое микрорайонирование, сейсмическое районирование, СМР, локальные грунтовые условия, оценка сейсмичности, уточнение исходной сейсмичности, УИС, эталонный грунт, сейсмологические исследования, сейсмотектонические исследования, площадка строительства, карты ОСР, общее сейсмическое районирование, Строительство в сейсмических районах, ответственные объекты, сейсмическая опасность, метод сейсмических жесткостей, подбор акселерограмм, тектонический разлом, период повторяемости землетрясений, сейсмические воздействия

Сейсморазведочные работы
- сейсморазведка, сейсмические волны, инженерная сейсморазведка, сейсмоприемник,  верхняя часть разреза, ВЧР, РСН 66-87, Скоростной разрез, годограф, МПВ, КМПВ, МОВ, ОГТ, MASW, оползневой участок

Электроразведочные работы
- Электроразведка, удельное электрическое сопротивление, диэлектрическая проницаемость, геоэлектрический разрез, вертикальное электрозондирование, ВЭЗ, электропрофилирование, ЭП, электротомография, ЭТ, 2D разрез

Оценка параметров собственных колебаний зданий
- тон собственных колебаний, состояние здания, декремент затухания, моды здания

Георадарные работы
- георадарное обследование, Георадиолокационное обследование

Анализ устойчивости геосреды на внешние воздействия
- промышленная безопасность, экологическая безопасность, оценка состояния окружающей среды, интенсификация скважины, численное моделирование, техногенные риски, геодеформационный процесс, геофизические материалы, техногенное землетрясение, промысловые сточные воды, закачка в пласт, буровой шлам, геосреда, продуктовый горизонт, добыча углеводородов,техногенное землетрясение, шельфовое месторождение

Разработка индивидуальной стратегии мониторинга геосреды
- арктические месторождения, опасные природные процессы, техногенные процессы, оползни, разжижение грунта, цунами, размывы берегов, извержение вулканов, сейсмические критерии, индивидуальная стратегия мониторинга,

**Comment by blackst0ne** [comment]
Ключевые слова добавил в задачу #4 

Этот тикет закрываю.
