### ISSUE TITLE
Добавить SEO-теги

### ISSUE THREAD

**Issue by blackst0ne** [geophystech/geophystech.ru#4]
Для успешного продвижения ресурса в поисковой выдаче поисковых систем, необходимо добавить соответствуюие теги в проект.  

Ссылки по теме:

1. https://github.com/kpumuk/meta-tags/blob/master/README.md
2. http://cookieshq.co.uk/posts/easy-seo-metatags-with-rails-4/

### Добавить keywords
Мониторинг естественной и наведённой сейсмичности:
- сейсмический мониторинг, сейсмологический мониторинг, геодинамический мониторинг, техногенная сейсмичность, естественная сейсмичность, землетрясение, интенсивность землетрясения, сейсмограмма, сейсмическая станция, сейсмостанция, магнитуда, MSK64

Мониторинг сильных движений грунта
- сильные движения грунта, эксплуатация промышленных объектов, сейсморазрыв, PGA, PGV, PGD, смещение земной поверхности, монтаж станций, магистральные объекты, трубопроводы

Сейсмометрический контроль зданий и сооружений
- Сейсмометрический контроль, сейсмостойкость, Строительство в сейсмических районах, гидротехнические сооружения, электростанции, сейсмические нагрузки, разрушение конструкции, спектр реакции, защита при ЧС, ТЭЦ, ГЭС, ГРЭС, АЭС, сейсмостойкое строительство

Сейсмическое микрорайонирование:
- Сейсмическое микрорайонирование, сейсмическое районирование, СМР, локальные грунтовые условия, оценка сейсмичности, уточнение исходной сейсмичности, УИС, эталонный грунт, сейсмологические исследования, сейсмотектонические исследования, площадка строительства, карты ОСР, общее сейсмическое районирование, Строительство в сейсмических районах, ответственные объекты, сейсмическая опасность, метод сейсмических жесткостей, подбор акселерограмм, тектонический разлом, период повторяемости землетрясений, сейсмические воздействия

Сейсморазведочные работы
- сейсморазведка, сейсмические волны, инженерная сейсморазведка, сейсмоприемник,  верхняя часть разреза, ВЧР, РСН 66-87, Скоростной разрез, годограф, МПВ, КМПВ, МОВ, ОГТ, MASW, оползневой участок

Электроразведочные работы
- Электроразведка, удельное электрическое сопротивление, диэлектрическая проницаемость, геоэлектрический разрез, вертикальное электрозондирование, ВЭЗ, электропрофилирование, ЭП, электротомография, ЭТ, 2D разрез

Оценка параметров собственных колебаний зданий
- тон собственных колебаний, состояние здания, декремент затухания, моды здания

Георадарные работы
- георадарное обследование, Георадиолокационное обследование

Анализ устойчивости геосреды на внешние воздействия
- промышленная безопасность, экологическая безопасность, оценка состояния окружающей среды, интенсификация скважины, численное моделирование, техногенные риски, геодеформационный процесс, геофизические материалы, техногенное землетрясение, промысловые сточные воды, закачка в пласт, буровой шлам, геосреда, продуктовый горизонт, добыча углеводородов,техногенное землетрясение, шельфовое месторождение

Разработка индивидуальной стратегии мониторинга геосреды
- арктические месторождения, опасные природные процессы, техногенные процессы, оползни, разжижение грунта, цунами, размывы берегов, извержение вулканов, сейсмические критерии, индивидуальная стратегия мониторинга,

**Comment by blackst0ne** [comment]
@jamm1985 нам нужен текст для `description` на каждой странице 
См. http://wiki.rookee.ru/meta-teg-description/

**Comment by jamm1985** [comment]
Главная
- Полный комплекс геофизических работ для изыскателей, строителей и проектировщиков.

Услуги
- Инженерная геофизика, сейсмический мониторинг и консультационные услуги.

О компании
- Инновационное предприятие Сахалина. Качество работ гарантировано командой профессионалов.

Контакты
- Контактная информация руководителей компании.

Реквизиты
- Регистрацонные данные и банковские реквизиты

Мониторинг естественной и наведённой сейсмичности
- Непрерывные сейсмологические наблюдения в составе геодинамического мониторинга

Мониторинг сильных движений грунта
- Обеспечение сейсмической безопасности на основе оперативной информации о движении грунта

Сейсмометрический контроль зданий и сооружений
- Непрерывные наблюдения за конструкциями объектов на базе сейсмических датчиков

Сейсмическое микрорайонирование
- Гарантия прохождения государственной экспертизы

Сейсморазведочные работы
- Полевые работы и анализ данных по преломленным (МПВ, КМПВ), отраженным (МОВ, ОГТ), поверхностным волнам (MASW)

Электроразведочные работы
- 1D, 2D, 3D разрезы. ВЭЗ и электротомография.

Оценка параметров собственных колебаний зданий
- Мониторинг технического состояния зданий и сооружений

Георадарные работы
- Результат - непрерывный разрез среды, в которой производится диагностика.

Анализ устойчивости геосреды на внешние воздействия
- Снижение природных и техногенных георисков. Обеспечение экологической и промышленной безопасности при промышленной разработке.

Разработка индивидуальной стратегии мониторинга геосреды
- Учёт всех опасных геологических рисков. Разработка плана наблюдений.
