### ISSUE TITLE
Поправить замечания от Google

### ISSUE THREAD

**Issue by blackst0ne** [geophystech/geophystech.ru#55]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fgeophystech.ru&tab=desktop

**Comment by jamm1985** [comment]
Добавил в конфигурацию:

```
...
  location ~* ^.+\.(jpg|jpeg|gif|png|ico|svg|ttf|woff|woff2|pdf|js|css)$ {
		expires 1w;
	}
...
```

**Comment by jamm1985** [comment]
Включил сжатие gzip.

Сейчас картина такая: mobile 67, desktop - 62

**Comment by jamm1985** [comment]
В варианте оптимизации картинок от гугла, самих картинок не видно. Можно попробовать уменьшить (немного) размер картинок из топа по загрузке, **но без видимой потери качества**.

Главная:
![2017-10-16 11 30 32](https://user-images.githubusercontent.com/3518847/31590966-97608a22-b265-11e7-8424-91353b70df5c.png)

Услуги:
![2017-10-16 11 32 18](https://user-images.githubusercontent.com/3518847/31590985-e1d9e8c8-b265-11e7-88cd-4f8608507a01.png)


ну и далее на страницах услуг

**Comment by blackst0ne** [comment]
Задеплоил часть оптимизаций.

**Comment by blackst0ne** [comment]
![image](https://user-images.githubusercontent.com/1610813/34801764-77e4349e-f6be-11e7-9538-7e1585f6bc72.png)
![image](https://user-images.githubusercontent.com/1610813/34801749-6a734fac-f6be-11e7-902e-62763e960fbe.png)

Для компьютеров попробую докрутить изображение одно, чтобы получить `99/100`.
С внешними скриптами аналитики я не знаю что пидумать. Они сейчас и так загружаются асинхронно + загрузка стартует только после загрузки всей страницы.

**Comment by blackst0ne** [comment]
![image](https://user-images.githubusercontent.com/1610813/34802092-dc2f7836-f6bf-11e7-8f04-8484a6943823.png)

Готово.

**Comment by blackst0ne** [comment]
Можно скачивать внешние скрипты аналитики на свой сервер раз в n часов/дней и затем отдавать уже с сервера эти скрипты. Тогда будет ещё быстрее. 

Но я не знаю, стоит ли усложнять эту всю штуку ради этого. 

@jamm1985 какие твои мысли на этот счёт?

**Comment by jamm1985** [comment]
Я думаю усложнять не стоит. Спасибо, хорошая работа!
