### ISSUE TITLE
Добавить фото на страницу с контактами

### ISSUE THREAD

**Issue by jamm1985** [geophystech/geophystech.ru#58]
Требуется добавить фотографии на страницу с контактами. Фото запрашивать напрямую у каждого специалиста, представленного на странице.

**Comment by blackst0ne** [comment]
Я думаю, что если фотографии будут в разных стилях, то получится цирк. 
Кто-то на лыжах, кто-то на пляже, кто-то в костюме и пр.

**Comment by jamm1985** [comment]
Да надо чисто лицо с плечами сделать да и всё. У всех есть такие фотки. У Константина и Алексея я точно видел, они их во все документы вставляют

**Comment by blackst0ne** [comment]
Все фотографии портретные, поэтому придётся изменить вёрстку страницу контактов, чтобы место использовалось эффективно. 
В планах разместить контакты не пирамидой, как сейчас, а списком: слева фотография, справа текст.

Как выглядит сейчас при добавлении портретной фотографии: 

![image](https://user-images.githubusercontent.com/1610813/32997896-e6f814e8-cde9-11e7-9a42-fd5f71d53f54.png)

**Comment by jamm1985** [comment]
Делай как будет лучше. Фото можно резать и подгонять под нужный размер при верстке.

**Comment by blackst0ne** [comment]
@jamm1985 готово.

https://geophystech.ru/contacts/

**Comment by blackst0ne** [comment]
@jamm1985 

Хотел сначала показать локально, как выглядит.
Но т.к. тебя сегодня нет, то залил на прод.

Если что-то нужно улучшить, пиши сюда.

**Comment by jamm1985** [comment]
@blackst0ne : 

Сейчас стало гораздо лучше. Главное замечание: картинки имеют те же url поэтому из кэша грузятся прямоугольные. Что бы посмотреть новый вариант, пришлось упражняться с девкитом хрома. У нас стоит 1 неделя кэша по статике в настройках веб-сервера. Я специально не буду чистить, посмотрим, как обновится страница. Тикет думаю можно закрывать. Если есть желание, можно ещё поупражняться  с текстом справа в рамках отдельной задачи. Может стоит интервал сделать одинаковый, текст более кучный и выравнивание по левому или правому краю....

**Comment by jamm1985** [comment]
@blackst0ne 

![2017-11-25 21 56 37](https://user-images.githubusercontent.com/3518847/33229852-a1aad786-d22b-11e7-914c-3177e211f0e6.jpg)

По просьбе Алексея требуется заменить его фото.

**Comment by blackst0ne** [comment]
@jamm1985 

Готово.
