### ISSUE TITLE
Добавить на главную ссылки на соцсети

### ISSUE THREAD

**Issue by jamm1985** [geophystech/geophystech.ru#59]
https://github.com/geophystech/

https://www.instagram.com/geophystech

**Comment by jamm1985** [comment]
и FB https://www.facebook.com/geophystech

**Comment by jamm1985** [comment]
и VK https://vk.com/geophystech

**Comment by jamm1985** [comment]
<img width="1393" alt="2017-11-11 23 26 47" src="https://user-images.githubusercontent.com/3518847/32689391-f1e13a32-c737-11e7-9ca3-8d91dc570f4d.png">

верстка едет

**Comment by jamm1985** [comment]
и самое главное - на мобиле иконок не видно... это ж ради мобилы и делается )

**Comment by blackst0ne** [comment]
@jamm1985 

На мобиле иконки добавляем в верхнюю часть экрана (меню) или в нижнюю часть экрана (подвал)?

**Comment by jamm1985** [comment]
Если на верх влезут, то лучше наверх. Если будут сильные сложности, то вниз.

**Comment by blackst0ne** [comment]
@jamm1985 

Готово.
