### ISSUE TITLE
Порядок картинок на странице сейсморазведочных работ

### ISSUE THREAD

**Issue by jamm1985** [geophystech/geophystech.ru#64]
на странице https://geophystech.ru/services/seismic-survey/ две одинаковые картинки:

![2017-11-16 18 42 54](https://user-images.githubusercontent.com/3518847/32879423-03f43778-cafe-11e7-828c-0e5f76bf6c01.png)

Нужно поднять ТЗ на верстку этой страницы и исправить ошибку.

**Comment by blackst0ne** [comment]
@jamm1985 не могу найти текста в issues.  
Может быть это было взято со старой версии сайта? :thinking: 

Где можно взять дамп БД предыдущей версии сайта?

**Comment by blackst0ne** [comment]
@jamm1985 

Готово.  
https://geophystech.ru/services/seismic-survey/
