### ISSUE TITLE
Поправить текст по сайту

### ISSUE THREAD

**Issue by jamm1985** [geophystech/geophystech.ru#65]
Требуется поправить текст по сайту согласно документу. Зелёный исправить, красный - удалить. 

[2017-10-18 Исправления по тексту на сайт.docx](https://github.com/geophystech/geophystech.ru/files/1484526/2017-10-18.docx)

**Comment by blackst0ne** [comment]
@jamm1985 

![image](https://user-images.githubusercontent.com/1610813/32996293-e936a068-cdd4-11e7-9aea-56878796b725.png)

По документу не очень понятно, что делать с текущим текстом (оставлять / заменять / удалять).

![image](https://user-images.githubusercontent.com/1610813/32996301-ff5eea3a-cdd4-11e7-8601-3d3b835ee83d.png)

**Comment by jamm1985** [comment]
Можно просто блоки поменять. Старый текст нужно удалить.

**Comment by blackst0ne** [comment]
@jamm1985 

1. Ссылка на страницу точна именно эта, а не https://geophystech.ru/services/seismic-monitoring-system/ ?
2. Куда вставлять новый текст? Этим текстом нужно заменить что-то текущее  (если да, то что нужно удалить?), или нужно просто добавить новый текст куда-то?

![image](https://user-images.githubusercontent.com/1610813/32996389-0deac154-cdd6-11e7-93ea-94ae9be8e37a.png)

**Comment by jamm1985** [comment]
> Ссылка на страницу точна именно эта, а не https://geophystech.ru/services/seismic-monitoring-system/ ?

У тебя ссылка правильная, у меня ошибка

Вот этот кусок заменить:

![2017-11-20 10 02 06](https://user-images.githubusercontent.com/3518847/32996685-f3f255ec-cdd9-11e7-8359-31278627f3af.png)

**Comment by blackst0ne** [comment]
@jamm1985 обновлено и задеплоено на прод.
