### ISSUE TITLE
Обновить раздел о Компании

### ISSUE THREAD

**Issue by jamm1985** [geophystech/geophystech.ru#85]
1. Поменять текст. 
[О Компании.docx](https://github.com/geophystech/geophystech.ru/files/1738406/default.docx)

2. Убрать большой интервал в разделе Кода видов.....

![2018-02-20 9 48 49](https://user-images.githubusercontent.com/3518847/36400178-8ab268fa-1623-11e8-9001-43fd82a1bf3f.png)

3. Обновить раздел лицензии и сертификаты. 
[Лицензии и сертификаты.docx](https://github.com/geophystech/geophystech.ru/files/1738453/default.docx)

**Comment by jamm1985** [comment]
[СВЕДЕНИЯ из из Единого реестра субъектов МСП.pdf](https://github.com/geophystech/geophystech.ru/files/1738460/default.pdf)

**Comment by jamm1985** [comment]
[ГЕОФИЗТЕХ_Выписка_из_реестра_членов_СРО.pdf](https://github.com/geophystech/geophystech.ru/files/1738615/_._._._._.pdf)

**Comment by blackst0ne** [comment]
@jamm1985 

В документе `Лицензии и сертификаты.docx` есть непонятный текст (выделено жирным). 

Что должно там быть? 

> На основании Решения Правления Ассоциации СРО «МРИ» №03-04-ПП/18 от 18.01.2018 г ООО «ГЕОФИЗТЕХ» наделено правом выполнять работы по инженерным изысканиям. Выписка из реестра членов СРО (СРО-И-035-26102012) №00089 от 18.01.2018 **[ссыка на выписку к тикету]**.

> ООО “ГЕОФИЗТЕХ” является субъектом малого предпринимательства **[ссылка на выписку к тикету]**. Компания аккредитована ПАО “НК РОСНЕФТЬ” для участия в закупочных процедурах **[ссылку на pdf пока нужно убрать]**.

**Comment by blackst0ne** [comment]
Я имел ввиду, на какой текст ссылки делать?

**Comment by blackst0ne** [comment]
1. Обновлено на продакшене. 
2. В `master` **не** слито пока не будет проверено. 

@jamm1985 проверяй.

**Comment by jamm1985** [comment]
![2018-03-13 15 36 34](https://user-images.githubusercontent.com/3518847/37322916-97e9b822-26d4-11e8-8b11-aeff0e23735c.png)

Прошу исправить ошибку. Ну и @blackst0ne прошу прочитать текст хотя бы разок. Я знаю, ты знаток русского языка, сразу все ошибки увидишь!

**Comment by blackst0ne** [comment]
Я добавляю ровно тот текст, который ты предоставил. Не перепечатываю его, а копирую и вставляю. 
Я исхожу из того, что текст вычитан, корректен и готов к эксплуатации. 👍🏻

**Comment by blackst0ne** [comment]
@jamm1985 

Обновлено.
